### ISSUE TITLE
Aot problem

### ISSUE THREAD

**Issue by OdaiTu** [DanielYKPan/date-time-picker#115]
on local everything okay but when doing aot comiple and make my app online the date-time-picker disapper 
but with --prod comipler its okay also

angular v 2.4.10
angular cli

![image](https://user-images.githubusercontent.com/12837840/29354917-b76fe772-8277-11e7-8ee0-5090e930a8a0.png)

**Comment by DanielYKPan** [comment]
so you mean when you run aot local,  the picker works fine?

**Comment by OdaiTu** [comment]
@DanielYKPan  i dont run it local with aot 
just ng s

but when make ng build --prod --aot
and upload the dist to my server the picker dont show !

**Comment by GeorgeKnap** [comment]
+1  I have the same problem. 
It has something to do with dynamically created components. see [#12885](https://github.com/angular/angular/issues/12885)

The worst part is it actually passes the AOT build without error but crashes at runtime.

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
Yes, I notice this issue. Right now I am reconstructing the whole picker (Not creating components dynamically as it is not necessary in this case).

**Comment by GeorgeKnap** [comment]
@DanielYKPan That's great! Looking forward to see the result.

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
I have redesigned the whole picker. Check it out and feel free to give some advice.

**Comment by GeorgeKnap** [comment]
Interesting. When I first click on datepicker it renders like this:
![datepicker](https://user-images.githubusercontent.com/11920691/29975162-b57d529a-8f35-11e7-8a32-7e7fe08bea86.PNG)
I have to change month to get  it rendered correctly and after closing and re-opening popup it behaves normally.

Oh, and I have to use `date-fns` version `1.x`. The 2-beta does not work, missing function `isToday`.
Anyway, bindings seems to work and aot build now looks good!
great job

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
When you open the picker first time, did you have any initial value?

**Comment by GeorgeKnap** [comment]
@DanielYKPan 
The initial value is `new Date()`

```
<owl-date-time formControlName="datetime" dateFormat="d.M.YYYY H:mm" [locale]="en"></owl-date-time>
```

```
this.reactiveForm= this.fb.group({
            datetime: new Date()
        });
```
I'll see if I can create a simple plunker.

**Comment by DanielYKPan** [comment]
@GeorgeKnap 
No need to create a plunker.
It has been fixed.
Download the beat-3 version, it should be all right.

**Comment by OdaiTu** [comment]
@DanielYKPan  what you mean by beat-3 version how to download it ?

**Comment by GeorgeKnap** [comment]
`"ng-pick-datetime": "5.0.0-beta.3"` in your `package.json`
Works for me.

**Comment by OdaiTu** [comment]
i still have this error with aot  !

![image](https://user-images.githubusercontent.com/12837840/30151148-01976870-93b7-11e7-926c-b58b52611679.png)

**Comment by GeorgeKnap** [comment]
@OdaiTu Do you have `@angular/animations` npm package installed?

**Comment by OdaiTu** [comment]
No !

**Comment by DanielYKPan** [comment]
In used angular animations, so you have to install it and import it in your app module

**Comment by OdaiTu** [comment]
@DanielYKPan  i used it now but aonther error comes up

![image](https://user-images.githubusercontent.com/12837840/30237968-60e96b30-9546-11e7-9ffd-a922edc42107.png)


and here is my code

`<div class="form-control input-rounded" 
                          name="date_to_publish"
                          #date_to_publish="ngModel" 
                          [hourTime]=" '12' " 
                          [mode]="'inline'" 
                          [(ngModel)]="selectedNews?.date_to_publish && selectedNews.date_to_publish"
                          [(dateTimePicker)]="selectedNews?.date_to_publish && selectedNews.date_to_publish" 
                          readonly 
                          [returnObject]="'string'" 
                          [viewFormat]= "'YYYY-MM-DD HH:mm'"
                          ></div>`

i changed it to input tag but its the same
