### ISSUE TITLE
close after select date 

### ISSUE THREAD

**Issue by christinegomes95** [DanielYKPan/date-time-picker#72]
Hi,
Not sure if I missed code specified;
On [pickerType]="'date'", automatically close after selecting the date?
Currently, after selecting the date, I have to close the dropdown by clicking outside the date-picker

**Comment by DanielYKPan** [comment]
@christinegomes95 
I do this intentionally. I think this makes more sence

**Comment by DanielYKPan** [comment]
@christinegomes95 
I would add an option to auto close the picker after selecting the date.

**Comment by DanielYKPan** [comment]
@christinegomes95 
Please update ng-pick-datetime to latest version.

I have added a option **[autoClose]**.
Set `**[autoClose]=" true "**`, the picker would close and return the moment value by clicking a day.

**Comment by christinegomes95** [comment]
Thank you so much, Daniel! Datepicker is a blessing!

**Comment by YGugnin** [comment]
Did you remove it? Can't find autoClose in your code

**Comment by DanielYKPan** [comment]
@YGugnin 
Yes, it has been removed.

**Comment by safwanazam** [comment]
@YGugnin can I know a way to autoClose calendar since you have removed the option in version 5?

**Comment by DanielYKPan** [comment]
I think it is just click outside the picker and the picker would be close. I guess autoClose is not necessary

**Comment by cristianoascari** [comment]
I think it would be useful. At least I miss this.

**Comment by DuncanMcIntyre** [comment]
Hi @DanielYKPan your DatePicker is awesome I like it. I agree with the others on having the autoClose though. The click outside works well on desktop browser, but when you're on mobile where you don't have much screen space - the datepicker ends up blocking you from clicking another field or a button. Would be nice to have the optional autoClose back.

**Comment by enavarro222** [comment]
I agree with @DuncanMcIntyre !

For now I found a workaround:
```
<owl-date-time #mydatepicker [(ngModel)]="model" (ngModelChange)='mydatepicker.hide()' >
</owl-date-time>
```

**Comment by YGugnin** [comment]
@safwanazam I just start using another plugin for it

**Comment by DanielYKPan** [comment]
@YGugnin  @safwanazam  @enavarro222 
Update the picker to version 5.0.0-beta.7

Now this is a [autoClose] property, which I guess is what you want. You could read more about this from README

**Comment by danielpiedra** [comment]
@DanielYKPan I did notice calendar won't close when clicking outside on 5.0.0-beta.12, has this functionality changed?

**Comment by mauricenaef** [comment]
Same here, latest version doesn't seem to autoClose on select. Any other way this can be achieved?

**Comment by juanhenriquez** [comment]
@DanielYKPan What happened with the `[autoClose]` property? We had this feature in v5.0.0-beta.11 and I just updated the package to v5.2.5 and now is gone! I think this property was very useful and shouldn't be removed. BTW you've made a good job with this library @DanielYKPan, thank you!

**Comment by DanielYKPan** [comment]
When you are using the picker as calendar, it would auto close after you select the date. But when you are using the picker as both calendar and timer, it would not auto close, as user may have to choose time after picker the date.

**Comment by Bhavana-Patil** [comment]
ng-pick-datetime used as a dialog if user clicks on cancel how to prevent it from setting date as I have used ngModel for that and it is setting date to other list item and fetching result for that.

<div class="list-group" *ngFor="let devices of devicesList | findDevice: searchText">
                      <button type="button" class="list-group-item list-group-item-action" [owlDateTimeTrigger]="dt5">
                          
                          {{devices.name}}
                          
                          <input [owlDateTime]="dt5" [(ngModel)]="selectedDateTime" class="hideInput" [min]="minDate" [max]="maxDate">
                          <owl-date-time [pickerMode]="'dialog'" #dt5 (afterPickerClosed)='getHistory(devices.imei_no,devices.remaining_days_to_expire,devices.name)'></owl-date-time>                         
                      </button>                
                     
                  </div>

**Comment by namrata7618** [comment]
@DanielYKPan I am using your datetim epicker with ng2-smart-table and i am facing two major issues.

1. Input field still showing time when I only select date.
2. When we select date and do (Add/Update) then date saving as current date not the date as I have selected

**Comment by Harshdeep86** [comment]
Hello @DanielYKPan,
I wanted to write a custom logic to handle the onCancelClicked() in datepicker...how can i do that
